Require `active_support` before cherry-picking features
It's part of the Active Support contract, the entry point
must be loaded, otherwise requiring individual components may
fail.

Fixes:

```
active_support/core_ext/time/conversions.rb:62:in `<class:Time>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)
	from gems/activesupport-7.1.1/lib/active_support/core_ext/time/conversions.rb:7:in `<top (required)>'
	from gems/activesupport-7.1.1/lib/active_support/core_ext/object/json.rb:14:in `require'
	from gems/activesupport-7.1.1/lib/active_support/core_ext/object/json.rb:14:in `<top (required)>'
	from gems/activesupport-7.1.1/lib/active_support/json/encoding.rb:3:in `require'
	from gems/activesupport-7.1.1/lib/active_support/json/encoding.rb:3:in `<top (required)>'
	from gems/activesupport-7.1.1/lib/active_support/json.rb:4:in `require'
	from gems/activesupport-7.1.1/lib/active_support/json.rb:4:in `<top (required)>'
	from gems/protobuf-cucumber-3.10.8/lib/protobuf.rb:10:in `require'
```